### ISSUE TITLE
sam build on maven project includes dependencies with scope "provided"

### ISSUE THREAD

**Issue by Spacemetric-Oscar** [aws/aws-lambda-builders#251] opened 2021-06-21 12:41 UTC
### Description:
sam build on maven project includes dependencies with scope "provided" when it should not be including these dependencies.

### Steps to reproduce:
Add <scope>provided</scope> to any dependency.

### Observed result:
Provided dependency is in the .aws-sam/<project>/build folder

### Expected result:
It should not be there

**Comment by cernertrevor** [comment] 2021-08-16 20:54
I agree that it should not include provided, and I've noticed a similar issue which is that it _doesn't_ include runtime, when I feel it should.

Ultimately, I feel like "sam build"s purpose is that it's generating the build artifacts to be directly used/uploaded by "sam deploy" which, in my mind, means the classpath it uses should be the equivalent of Maven's "runtime" classpath (which includes "compile" and "runtime", but excludes "provided").  This makes the resulting files "ready-to-go" as it were by whatever "container" (in this case Lambda) they run from.  I'm wondering if this is just as simple as changing the dependency-copy here:

https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_maven/maven.py#L37

From:
```
args = ["dependency:copy-dependencies", "-DincludeScope=compile", "-Dmdep.prependGroupId=true"]
```

To:
```
args = ["dependency:copy-dependencies", "-DincludeScope=runtime", "-Dmdep.prependGroupId=true"]
```

**Comment by RajasGujarathi** [comment] 2021-09-24 14:26
Duplicate of #2047

**Comment by admendoz25** [comment] 2022-03-16 20:30
I am running into a similar issue. I have an AWS Lambda written in Java + maven, and I bring in:
```
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>ssm</artifactId>
      <version>${ssm.version}</version>
    </dependency>
```

The `ssm` dependency should bring in
```
<dependency>
            <artifactId>apache-client</artifactId>
            <groupId>software.amazon.awssdk</groupId>
            <version>${awsjavasdk.version}</version>
            <scope>runtime</scope>
</dependency>
```
via its parent. See https://github.com/aws/aws-sdk-java-v2/blob/master/services/pom.xml#L379-L384

When SAM packages my function, I run into the following issue:
```
"Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder"
```

I did what @s-parvizi recommended here https://github.com/aws/aws-sam-cli/issues/3185 and it works. But essentially sam cli is not honoring my build configuration specified in my pom.xml

**Comment by cernertrevor** [comment] 2022-03-16 20:47
@admendoz25 
What version of SAM are you using?  The fix for this was recently implemented (but put behind a feature flag initially due to it breaking expectations with how it was working before (even though it was wrong)) in 1.38.0.

See here:
https://github.com/aws/aws-sam-cli/issues/2047

**Comment by mndeveci** [comment] 2022-04-25 17:13
We've released some changes recently, which should address the issue here. Please let us know if you still experience any issues by commenting in SAM CLI announcement issue: https://github.com/aws/aws-sam-cli/issues/3639

**Closed by mndeveci** 2022-04-25 17:13 UTC
Labels: type/bug, maintainer/need-response
