### ISSUE TITLE
Issues deploying dotnetcore3.1 lambda using sam build & deploy

### ISSUE THREAD

**Issue by cj930736** [aws/aws-lambda-builders#188] opened 2020-07-28 07:06 UTC
**Description:**

Hi,

When deploying a dotnetcore3.1 lambda using "sam build" followed by "sam depoy" I am getting the following error in the cloudwatch logs:-

Could not find the required 'LambdaA1Importer.deps.json'.  This file should be present at the root of the deployment package.: LambdaException

I have checked the zip file uploaded by SAM and the dependency file is definitely in there. When I follow up the deployment with the following comand:-

"dotnet lambda deploy-function <functon-name> -role <functon-role>

The lambda is then deployed. Is there something missing in the sam build/ sam deploy stage?

Kind Regards

Chris Jackson

**Comment by sriram-mv** [comment] 2021-07-30 21:50
I'm unable to reproduce this, I used the dotnet3.1 helloworld application and the app built and deployed successfully. I'm closing this issue. please re-open if its still an issue.

**Closed by sriram-mv** 2021-07-30 21:50 UTC
Labels: area/workflow/dotnet_clipackage, type/bug
