### ISSUE TITLE
sam build is not honoring package-lock.json

### ISSUE THREAD

**Issue by wernerwws** [aws/aws-lambda-builders#221] opened 2021-01-18 11:42 UTC
### Description:
To be able to have reproducible builds I have my package-lock.json checked in. However `sam build` is not copying the package-lock file to the corresponding Lamba function directory in .aws-sam/build.

### Steps to reproduce:

1. Run `sam init` -> "1 - AWS Quick Start Templates" -> "1 - Zip (artifact is a zip uploaded to S3)" -> "1 - nodejs12.x" -> "1 - Hello World Example"
2. `cd sam-app`
3. `(cd hello-word && npm i)`
5. `sam-build`
6. `ls -alh .aws-sam/build/HelloWorldFunction`

### Observed result:
There is `package-lock.json` is not copied over and therefor `npm install` can not install the exact dependency tree need to have a reproducible build.

### Expected result:
The `package-lock.json` file should be taken into account if it is available.

**Comment by mgrandis** [comment] 2021-01-19 01:42
We are using `npm pack` to package dependencies before installing.
It seems that it is not packing the `package-lock.json` file.
We may have to copy it by hand.

**Comment by wernerwws** [comment] 2021-01-19 08:54
@mgrandis Thank you - I think you directed me in the right direction.

`npm pack` is not honoring the `package-lock.json` intentionally; however, it uses another lock file called `npm-shrinkwrap.json`.

The `npm-shrinkwrap.json` is replacing the `package-lock.json` if it is present and takes precedence over it.

Now, the solution is to work with the `npm-shrinkwrap.json` instead of the `package-lock.json`.

I think you can close this enhancement. For more information, see here:

https://stackoverflow.com/questions/60925417/npm-pack-and-missing-package-lock-json
https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json
https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

**Comment by mgrandis** [comment] 2021-01-19 17:11
@wernerwws Glad to hear!

Before I close this issue, have you been able to test and confirm that this was indeed working as intended with `npm-shrinkwrap.json`?

**Comment by wernerwws** [comment] 2021-01-19 20:23
I tested that `sam build` with `npm pack` copies the `npm-shrinkwrap.json` into the `.aws-sam/build/...` directories and that the `npm install` executed there, used the `npm-shrinkwrap.json` file to pin the version for one problematic library I had issues with.

So I think you can close it, if I see any issues in the future we can reopen the issue anyway.

**Comment by mgrandis** [comment] 2021-01-19 21:31
Thanks!

**Closed by mgrandis** 2021-01-19 21:31 UTC
Labels: area/workflow/node_npm, enhancement
