### ISSUE TITLE
Python version validation fails in CircleCI cimg/python3.9

### ISSUE THREAD

**Issue by Willbly** [aws/aws-lambda-builders#281] opened 2021-09-15 06:46 UTC
**Description:**

When using the SAM CLI, it calls this library which then fails when trying to validate the installed Python version despite there being a valid installation. Interestingly the legacy image `circleci/python:3.9.6` works fine.

**Steps to reproduce the issue:**
1. Create a CircleCI pipeline with the executor image `cimg/python:3.9.6`
2. Run `sam build` with any template file

**Observed result:**
The command fails when trying to validate the Python version with these logs:
```
2021-09-10 01:43:20,142 | Invalid executable for python at /home/circleci/.pyenv/shims/python3.9
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 58, in wrapper
  File "aws_lambda_builders/workflows/python_pip/validator.py", line 48, in validate
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime. 
 Expected version: python3.9, Found version: /home/circleci/.pyenv/shims/python3.9. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
2021-09-10 01:43:20,157 | Invalid executable for python at /home/circleci/.pyenv/shims/python
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 58, in wrapper
  File "aws_lambda_builders/workflows/python_pip/validator.py", line 48, in validate
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime. 
 Expected version: python3.9, Found version: /home/circleci/.pyenv/shims/python. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
```

**Expected result:**
The command completes succesfully.

**Other notes**
When running the command generated by the validation module python_pip.validator manually like so:
```bash
/home/circleci/.pyenv/shims/python3.9 -c "import sys; assert sys.version_info.major == 3 and sys.version_info.minor == 9"
```
it completes successfully. This works with all Python versions found on the PATH checked by the validator.

**Comment by hoffa** [comment] 2021-09-17 01:19
I'm unable to reproduce with these steps:

```bash
docker run --rm -it cimg/python:3.9.6

# From inside container
pip install aws-sam-cli
sam init --name sam-app --runtime python3.9 --dependency-manager pip --app-template hello-world
cd sam-app
sam build
```

Anything I'm missing?

**Comment by Willbly** [comment] 2021-09-24 05:43
We're installing the SAM CLI via the CircleCI-provided orb [circleci/aws-sam-serverless@3.1.0](https://circleci.com/developer/orbs/orb/circleci/aws-sam-serverless) rather than with pip. Their install method looks something like this:
```
curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli-linux-x86_64.zip
unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
sudo ./sam-installation/install
```
This may have something to do with it.

**Comment by ssenchenko** [comment] 2021-12-09 03:18
Closing because it's impossible to reproduce.

**Closed by ssenchenko** 2021-12-09 03:18 UTC
Labels: area/workflow/python_pip, blocked/more-info-needed, maintainer/need-followup
