### ISSUE TITLE
Ruby builder should report bundler errors

### ISSUE THREAD

**Issue by jasonmk** [aws/aws-lambda-builders#76] opened 2019-02-05 18:05 UTC
**Description:**

When sam build fails on a ruby project, the error output from bundler just gets lost.  Even with --debug, it doesn't print out.

In the same vein (debugging ruby build issues), when --debug is passed to sam, this should IMO automatically pass the --verbose flag to bundler.

**Steps to reproduce the issue:**
1. Create a SAM project with the ruby runtime
2. Add a bogus gem to Gemfile
3. Run sam build

**Observed result:**

2019-02-05 18:03:16 'ruby' runtime has not been validated!
2019-02-05 18:03:16 Running RubyBundlerBuilder:CopySource
2019-02-05 18:03:16 Running RubyBundlerBuilder:RubyBundle
Build Failed
Error: RubyBundlerBuilder:RubyBundle - Bundler Failed:

**Expected result:**

Bundler error about unknown gem should be displayed.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

aws-lambda-builders 0.0.5
aws-sam-cli         0.10.0
aws-sam-translator  1.9.0

**Comment by RedaBenh** [comment] 2019-03-16 13:00
+1
Realy frustrating !
if we can't see the error we can't fix it !

**Comment by jfuss** [comment] 2019-11-05 20:47
@RedaBenh and @jasonmk Are you guys by chance installing SAM CLI in python2.7? I do not see this on Python3.7. Given SAM CLI dropped support for installing with Python2.7, I would suggest upgrading.

**Comment by jfuss** [comment] 2019-11-06 15:00
Looks like there are cases in which `bundler` send important information to stdout instead of stderr. An example of this is: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-w4jmj/builds/28660090#L350

```
INFO     tests.integration.buildcmd.test_build_cmd:test_build_cmd.py:234 executing Bundler: ['bundler.bat', 'install', '--without', 'development', 'test']
INFO     tests.integration.buildcmd.test_build_cmd:test_build_cmd.py:244 STDOUT: Fetching source index from https://rubygems.org/
                                                                         Resolving dependencies...
                                                                         Could not verify the SSL certificate for
                                                                         https://rubygems.org/quick/Marshal.4.8/aws-record-2.4.0.gemspec.rz.
                                                                         There is a chance you are experiencing a man-in-the-middle attack, but most
                                                                         likely your system doesn't have the CA certificates needed for verification. For
                                                                         information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
                                                                         without using SSL, edit your Gemfile sources and change 'https' to 'http'.
INFO     tests.integration.buildcmd.test_build_cmd:test_build_cmd.py:245 STDERR: 
INFO     tests.integration.buildcmd.test_build_cmd:test_build_cmd.py:276 Building resource 'Function'
                                                                         Running RubyBundlerBuilder:CopySource
                                                                         Running RubyBundlerBuilder:RubyBundle
                                                                         executing Bundler: ['bundler.bat', 'install', '--without', 'development', 'test']
                                                                         STDOUT: Fetching source index from https://rubygems.org/
                                                                         Resolving dependencies...
                                                                         Could not verify the SSL certificate for
                                                                         https://rubygems.org/quick/Marshal.4.8/aws-record-2.4.0.gemspec.rz.
                                                                         There is a chance you are experiencing a man-in-the-middle attack, but most
                                                                         likely your system doesn't have the CA certificates needed for verification. For
                                                                         information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
                                                                         without using SSL, edit your Gemfile sources and change 'https' to 'http'.
                                                                         
                                                                         STDERR: 
                                                                         
                                                                         Build Failed
                                                                         Error: RubyBundlerBuilder:RubyBundle - Bundler Failed:
```

I was testing the case of a gem that does not exist yesterday, which results in the expected behavior of output from bundler and SAM CLI. That is bundler sends the information to STDERR and SAM CLI puts that into the exception we throw.

**Comment by macejmic** [comment] 2019-11-21 01:10
It has been fixed in Bundler 2.0 https://github.com/bundler/bundler/issues/3353

**Comment by prcongithub** [comment] 2020-10-08 06:30
Are you using the same ruby version in Gemfile and SAM template? I faced this with mismatch of ruby version at these two places. But better error explanation would definitely help, anyway.

**Comment by omenking** [comment] 2020-12-19 18:37
Not sure why I'm getting it. Correct ruby version 🤷‍♂️
```
Fetching amazon/aws-sam-cli-build-image-ruby2.7 Docker container image......
Mounting /Users/andrewbrown/Sites/teacherseat/evaluators/evaluator_ruby as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running RubyBundlerBuilder:CopySource
Running RubyBundlerBuilder:RubyBundle
Error: RubyBundlerBuilder:RubyBundle - Bundler Failed:
```

**Comment by take2webservice** [comment] 2021-02-03 14:25
In my case, I update Ruby's version from 2.5.0 to 2.5.8 and this problem is resolved.

`sam build` command can use `--debug` option.
When I execute `sam build --debug`, I got stdout below

```
2021-02-03 22:45:36,362 | Running bundle install in /Users/username/test/ruby_lambda/sam-app/.aws-sam/build/HelloWorldFunction
2021-02-03 22:45:36,362 | executing Bundler: ['bundle', 'install', '--without', 'development', 'test']
2021-02-03 22:45:37,471 | RubyBundlerBuilder:RubyBundle failed
Traceback (most recent call last):
```
When I execute `bundle install` in  the directory `HelloWorldFunction`, some error was happened.
(sorry i forgot to capture logs. I think it was openssl version error.)

So I update Ruby version, it was resoleved.

**Comment by frbl** [comment] 2021-03-30 19:59
had the same issue, and @take2webservice really helped. I had to set the ruby version to the correct version (2.5 in Lambda's case)

**Closed** 2021-07-30 21:52 UTC
Labels: type/bug
