### ISSUE TITLE
Bug: recursively copies artifact dir when it's in source dir

### ISSUE THREAD

**Issue by israelg99** [aws/aws-lambda-builders#382] opened 2022-08-13 10:40 UTC
Recursively copies artifact dir when it's in source dir until it errors out:

JSON-RPC input:
```json
{
...
"source_dir":    "path/to/source",
"artifacts_dir":  "path/to/source/.build/artifact",
...
}
```

Then running `lambda-builders <JSON INPUT>`

Results in
```bash
PythonPipBuilder:CopySource - [Errno 63] File name too long: '/path/to/source/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/.build/artifact/python_dateutil-2.8.2.dist-info/top_level.txt'
```

Setting `artifact_dir` outside the `source_dir` solves this issue.

----

**Is this a bug, or is this expected? Perhaps we should add `ignore: {}` interface? I can contribute a PR for this if you guys can point me in the right direction.**

----

#### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`:
3. AWS region: us-east-1 (shouldn't matter)

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment] 2022-08-16 12:47
@israelg99 `artifact_dir` and `source_dir` should be different directories unless you wanted to embed (and copy them) for some reason. To my knowledge, we don't want to restrict the behavior here so we don't want to fail the run. Maybe we should? But not sure what that could break now, if we do.

On the `ignore` interface, I am not sure. It seems like a good idea and something we might be able to leverage in SAM CLI to ignore different directories or files. I can check with the team on the support. My concern is more about making sure we have the right scope and not locking ourselves into something we couldn't expand. For example, we would need to make sure its something we can support in SAM CLI, as I know customers have wanted support for ignoring files in their source. Your ask seems slightly different (maybe it isn't) but my point is we just need to really think through all the use-cases for something like this.

In the mean time, my suggestion is to use separate directories for each as this was how Lambda Builders (and SAM CLI) was designed.

**Comment by pkit** [comment] 2023-01-14 00:13
@jfuss 
> In the mean time, my suggestion is to use separate directories for each as this was how Lambda Builders (and SAM CLI) was designed.

Err... how exactly it should be done?
Copying all the files three times or what?
Let's think about a typical project:
```
/home/user/my_project/
/home/user/my_project/main.py
/home/user/my_project/requirements.txt
/home/user/my_project/my_module/
/home/user/my_project/my_module/module.py
```
What's the proposed solution for building this one?
Typical solution:
```
/home/user/my_project/.build
```
will fail miserably because of that strange behavior.

**Comment by pkit** [comment] 2023-01-14 16:03
Ah, this one is so cute!
https://github.com/aws/aws-lambda-builders/blob/cefc3315e82fb70458649a4061e50c9d0279816f/aws_lambda_builders/workflows/python_pip/workflow.py#L26
https://github.com/aws/aws-lambda-builders/blob/75927e35f7b91c5ca93d1800a406ac0d54e7dbac/aws_lambda_builders/workflows/ruby_bundler/workflow.py#L26
https://github.com/aws/aws-lambda-builders/blob/75927e35f7b91c5ca93d1800a406ac0d54e7dbac/aws_lambda_builders/workflows/java_maven/workflow.py#L29
https://github.com/aws/aws-lambda-builders/blob/75927e35f7b91c5ca93d1800a406ac0d54e7dbac/aws_lambda_builders/workflows/nodejs_npm/workflow.py#L41
So, `aws-sam` does suffer from the same bug, but you just hardcoded the escape hatch...
Nice!

**Comment by israelg99** [comment] 2023-01-14 18:47
@pkit Agreed. I think exposing this escape hatch with some `ignore: ` interface would be helpful.

**Comment by torresxb1** [comment] 2023-01-18 21:45
We have a few issues asking for a similar thing in `ignore:` or a `.samignore` file. Closing so that we can track here: https://github.com/aws/aws-lambda-builders/issues/185

**Closed by torresxb1** 2023-01-18 21:45 UTC
Labels: type/feature, maintainer/need-followup
